### ISSUE TITLE
Doesn't work on Wayland

### ISSUE THREAD

**Issue by adwaymalhotra** [adamsoutar/velocity#1]
It seems wayland is not supported in SFML.
```
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
```

**Comment by adamsoutar** [comment]
As of https://github.com/adamsoutar/velocity/commit/2d01a24a0c5c33fa5e55ea2c6767b813ae69f595 , velocity *should* work on Wayland machines without X back-compat.

Just `cargo run` from `/velocity-sdl`. The port is less complete than SFML (arrow keys, Ctrl modifiers etc. don't work yet), but it should be enough to check if porting to SDL can provide Wayland support.
